# Makefile for project 0
#
# CMSC 22600 --- Compilers for Computer Languages
# Autumn 2021
# University of Chicago
#
# COPYRIGHT (c) 2021 John Reppy (http://cs.uchicago.edu/~jhr)
# All rights reserved.
#
# targets:
#	make lambda-eval	-- build Lambda-calculus evaluator
#	make clean		-- remove intermediate files
#

SHELL =         /bin/sh

# we assume that sml (and thus ml-build is in the path)
#
ML_BUILD =	ml-build

HEAP_SUFFIX =	$(shell sml @SMLsuffix)

PROGRAM =	lambda-eval

CM_FILES =	src/sources.cm
HEAP =		$(PROGRAM).$(HEAP_SUFFIX)
TARGET =	bin/$(HEAP)

SRCS =		src/eval.sml \
		src/lambda.sml \
		src/main.sml

# build rule for evaluator
$(TARGET):	$(CM_FILES) $(SRCS)
	$(ML_BUILD) src/sources.cm Main.main $(PROGRAM)
	mv $(HEAP) bin

# remove generated files (including the files generated by ml-antlr and ml-ulex)
#
.PHONY:		clean
clean:
		rm -rf $(TARGET)
		rm -rf .cm */.cm
